=== brad-jones/teamcity-playground/project-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

	<xsd:element name='project'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='name' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='description' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref="default-template" minOccurs='0' maxOccurs='1'/>
				<xsd:choice minOccurs='0' maxOccurs='unbounded'>
					<xsd:element ref='parameters'/>
					<xsd:element ref='project-extensions'/>
					<xsd:element ref='cleanup'/>
					<xsd:element ref='buildTypesOrder'/>
					<xsd:element ref='subprojectsOrder'/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='parent-id' type='externalId' use='optional'/>
			<xsd:attribute name='archived' use='optional' type="booleanString"/>
			<xsd:attribute name='uuid' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='template'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='name' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='description' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='settings'/>
			</xsd:sequence>
			<xsd:attribute name='uuid' type='xsd:string' use='optional'/>
			<xsd:attribute name='name' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='enforcedSettings'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="settings" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:attribute name='ref' type='externalId'/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='build-type'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='name' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='description' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='settings'/>
			</xsd:sequence>
			<xsd:attribute name='uuid' type='xsd:string' use='optional'/>
			<xsd:attribute name='name' type='xsd:string' use='optional'/>
			<xsd:attribute name='paused' use='optional' type="booleanString"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='name'>
		<xsd:complexType mixed='true'>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='description'>
		<xsd:complexType mixed='true'>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='settings'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='inherits' minOccurs='0' maxOccurs='1' />
				<xsd:element ref='options' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='disabled-settings' minOccurs='0' maxOccurs='1'/>
				<xsd:choice minOccurs='0' maxOccurs='unbounded'>
					<xsd:element ref='parameters'/>
					<xsd:element ref='build-runners'/>
					<xsd:element ref='build-extensions'/>
					<xsd:element ref='vcs-settings'/>
					<xsd:element ref='requirements'/>
					<xsd:element ref='build-triggers'/>
					<xsd:element ref='artifact-dependencies'/>
					<xsd:element ref='dependencies'/>
					<xsd:element ref='cleanup'/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name='ref' type='externalId' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='inherits'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='ref'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='ref'>
		<xsd:complexType>
			<xsd:attribute name="id" type='externalId' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='disabled-settings'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='setting-ref'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='setting-ref'>
		<xsd:complexType>
			<xsd:attribute name='ref' type='externalId' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='build-runners'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='runner'/>
			</xsd:sequence>
			<xsd:attribute name='order' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='runner'>
		<xsd:complexType>
			<xsd:choice minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='conditions'/>
				<xsd:element ref='parameters'/>
			</xsd:choice>
			<xsd:attribute name='id' type='externalId' use='optional'/>
			<xsd:attribute name='type' type='xsd:string' use='required'/>
			<xsd:attribute name='name' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='build-extensions'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='extension'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='project-extensions'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='extension'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='extension'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='parameters'/>
			</xsd:sequence>
			<xsd:attribute name='id' type='externalId' use='optional'/>
			<xsd:attribute name='type' type='xsd:string' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='vcs-settings'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='vcs-entry-ref'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='vcs-entry-ref'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='checkout-rule'/>
			</xsd:sequence>
			<xsd:attribute name='root-id' type='externalId' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='checkout-rule'>
		<xsd:complexType>
			<xsd:attribute name='rule' type='xsd:string' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='cleanup'>
		<xsd:complexType>
			<xsd:choice minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='options'/>
				<xsd:element ref='policy'/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='vcs-root'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='name' minOccurs='0' maxOccurs='1'/>
				<xsd:element ref='param' minOccurs='0' maxOccurs='unbounded'/>
			</xsd:sequence>
			<xsd:attribute name='uuid' type='xsd:string' use='optional'/>
			<xsd:attribute name='name' type='xsd:string' use='optional'/>
			<xsd:attribute name='type' type='xsd:string' use='required'/>
			<xsd:attribute name='modification-check-interval' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='requirements'>
		<xsd:complexType>
			<xsd:choice minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='any'/>
				<xsd:element ref='exists'/>
				<xsd:element ref='not-exists'/>
				<xsd:element ref='equals'/>
				<xsd:element ref='does-not-equal'/>
				<xsd:element ref='more-than'/>
				<xsd:element ref='no-more-than'/>
				<xsd:element ref='less-than'/>
				<xsd:element ref='no-less-than'/>
				<xsd:element ref='contains'/>
				<xsd:element ref='does-not-contain'/>
				<xsd:element ref='starts-with'/>
				<xsd:element ref='ends-with'/>
				<xsd:element ref='matches'/>
				<xsd:element ref='does-not-match'/>
				<xsd:element ref='ver-more-than'/>
				<xsd:element ref='ver-no-more-than'/>
				<xsd:element ref='ver-less-than'/>
				<xsd:element ref='ver-no-less-than'/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='conditions'>
		<xsd:complexType>
			<xsd:choice minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='any'/>
				<xsd:element ref='exists'/>
				<xsd:element ref='not-exists'/>
				<xsd:element ref='equals'/>
				<xsd:element ref='does-not-equal'/>
				<xsd:element ref='more-than'/>
				<xsd:element ref='no-more-than'/>
				<xsd:element ref='less-than'/>
				<xsd:element ref='no-less-than'/>
				<xsd:element ref='contains'/>
				<xsd:element ref='does-not-contain'/>
				<xsd:element ref='starts-with'/>
				<xsd:element ref='ends-with'/>
				<xsd:element ref='matches'/>
				<xsd:element ref='does-not-match'/>
				<xsd:element ref='ver-more-than'/>
				<xsd:element ref='ver-no-more-than'/>
				<xsd:element ref='ver-less-than'/>
				<xsd:element ref='ver-no-less-than'/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='options'>
		<xsd:complexType>
			<xsd:sequence maxOccurs='unbounded'>
				<xsd:element ref='option'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='option'>
		<xsd:complexType>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='spec' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='dependencies'>
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs='unbounded'>
				<xsd:element ref='depend-on'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='depend-on'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='1'>
				<xsd:element ref='options'/>
			</xsd:sequence>
			<xsd:attribute name='sourceBuildTypeId' type='externalId' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='artifact-dependencies'>
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs='unbounded'>
				<xsd:element ref='dependency'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='dependency'>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref='revisionRule'/>
				<xsd:sequence maxOccurs='unbounded'>
					<xsd:element ref='artifact'/>
				</xsd:sequence>
			</xsd:sequence>
			<xsd:attribute name='sourceBuildTypeId' type='externalId' use='required'/>
			<xsd:attribute name='cleanDestination' use='optional' type="booleanString"/>
			<xsd:attribute name='id' use='optional' type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='revisionRule'>
		<xsd:complexType>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='revision' type='xsd:string' use='optional'/>
			<xsd:attribute name='branch' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='artifact'>
		<xsd:complexType>
			<xsd:attribute name='sourcePath' type='xsd:string' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='build-triggers'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='build-trigger'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='build-trigger'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='parameters'/>
			</xsd:sequence>
			<xsd:attribute name='id' type='externalId' use='optional'/>
			<xsd:attribute name='type' type='xsd:string' use='required'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='parameters'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='param'/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='default-template'>
		<xsd:complexType>
			<xsd:attribute name='ref' type='externalId' use='required' />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='policy'>
		<xsd:complexType>
			<xsd:sequence minOccurs='0' maxOccurs='unbounded'>
				<xsd:element ref='parameters'/>
			</xsd:sequence>
			<xsd:attribute name='type' type='xsd:string' use='required'/>
			<xsd:attribute name='cleanup-level' use='optional'>
				<xsd:simpleType>
					<xsd:restriction base='xsd:string'>
						<xsd:enumeration value='EVERYTHING'/>
						<xsd:enumeration value='HISTORY_ENTRY'/>
						<xsd:enumeration value='ARTIFACTS'/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='param'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='optional'/>
			<xsd:attribute name='spec' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='contains'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='does-not-contain'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='no-less-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='ver-no-less-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='ends-with'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='less-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='ver-less-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='any'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='exists'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='not-exists'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='more-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='ver-more-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='starts-with'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='no-more-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='ver-no-more-than'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='equals'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='does-not-equal'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='matches'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name='does-not-match'>
		<xsd:complexType mixed='true'>
			<xsd:attribute name='name' type='xsd:string' use='required'/>
			<xsd:attribute name='value' type='xsd:string' use='required'/>
			<xsd:attribute name='id' type='xsd:string' use='optional'/>
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="booleanString">
		<xsd:restriction base='xsd:string'>
			<xsd:enumeration value='true'/>
			<xsd:enumeration value='false'/>
			<xsd:enumeration value='yes'/>
			<xsd:enumeration value='no'/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="externalId">
		<xsd:restriction base='xsd:string'/>
	</xsd:simpleType>

	<xsd:element name="buildTypesOrder">
		<xsd:complexType>
			<xsd:attribute name="order" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="subprojectsOrder">
		<xsd:complexType>
			<xsd:attribute name="order" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== brad-jones/teamcity-playground/.teamcity/Test1/vcsRoots/ABC123.xml
<?xml version="1.0" encoding="UTF-8"?>
<vcs-root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="03a4ac21-8dc7-4ec2-b4ad-5d74046c8379" type="jetbrains.git" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>BarBaz</name>
  <param name="agentCleanFilesPolicy" value="ALL_UNTRACKED" />
  <param name="agentCleanPolicy" value="ON_BRANCH_CHANGE" />
  <param name="authMethod" value="PRIVATE_KEY_FILE" />
  <param name="branch" value="master" />
  <param name="ignoreKnownHosts" value="true" />
  <param name="privateKeyPath" value="/foo/bar/baz.pem" />
  <param name="secure:passphrase" value="zxx2b4d581dd842317df16da29ef3ff4cf0" />
  <param name="secure:password" value="" />
  <param name="submoduleCheckout" value="CHECKOUT" />
  <param name="teamcity:branchSpec"><![CDATA[+:foo
-:bar]]></param>
  <param name="url" value="git@github.com:brad-jones/teamcity-playground.git" />
  <param name="username" value="adsfghadfhsdfgjh" />
  <param name="usernameStyle" value="USERID" />
</vcs-root>

=== brad-jones/teamcity-playground/.teamcity/Test1_SubProject1/buildTypes/Test1_SubProject1_PackageWin.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="f80e94c1-9ebe-4d82-8a23-0235d7db5e8f" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>Package-Win</name>
  <description />
  <settings>
    <parameters />
    <build-runners>
      <runner id="RUNNER_6" name="" type="simpleRunner">
        <parameters>
          <param name="script.content" value="echo &quot;Hello World&quot;;" />
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
    </build-runners>
    <vcs-settings>
      <vcs-entry-ref root-id="Test1_GithubComBradJonesTeamcityPlayground" />
    </vcs-settings>
    <requirements />
    <build-triggers />
    <cleanup />
  </settings>
</build-type>

=== brad-jones/teamcity-playground/.teamcity/Test1/vcsRoots/Test1_BarBaz.xml
<?xml version="1.0" encoding="UTF-8"?>
<vcs-root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="03a4ac21-8dc7-4ec2-b4ad-5d74046c8379" type="jetbrains.git" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>BarBaz</name>
  <param name="agentCleanFilesPolicy" value="ALL_UNTRACKED" />
  <param name="agentCleanPolicy" value="ON_BRANCH_CHANGE" />
  <param name="authMethod" value="ANONYMOUS" />
  <param name="branch" value="master" />
  <param name="ignoreKnownHosts" value="true" />
  <param name="submoduleCheckout" value="CHECKOUT" />
  <param name="url" value="https://github.com/brad-jones/teamcity-playground.git" />
  <param name="useAlternates" value="true" />
  <param name="usernameStyle" value="USERID" />
</vcs-root>

=== brad-jones/teamcity-playground/.teamcity/Test1_SubProject1/buildTypes/Test1_SubProject1_PackageLin.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="f327b3b0-4272-4788-9772-5f210b0ff74b" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>Package-Lin</name>
  <description />
  <settings>
    <parameters />
    <build-runners>
      <runner id="RUNNER_7" name="" type="simpleRunner">
        <parameters>
          <param name="script.content" value="echo &quot;Hello World&quot;;" />
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
    </build-runners>
    <vcs-settings>
      <vcs-entry-ref root-id="Test1_GithubComBradJonesTeamcityPlayground" />
    </vcs-settings>
    <requirements />
    <build-triggers>
      <build-trigger id="vcsTrigger" type="vcsTrigger">
        <parameters>
          <param name="branchFilter" value="+:*" />
          <param name="enableQueueOptimization" value="true" />
          <param name="quietPeriodMode" value="DO_NOT_USE" />
        </parameters>
      </build-trigger>
    </build-triggers>
    <dependencies>
      <depend-on sourceBuildTypeId="Test1_SubProject1_Test">
        <options>
          <option name="run-build-if-dependency-failed" value="RUN_ADD_PROBLEM" />
          <option name="take-started-build-with-same-revisions" value="true" />
          <option name="take-successful-builds-only" value="true" />
        </options>
      </depend-on>
    </dependencies>
    <cleanup />
  </settings>
</build-type>

=== brad-jones/teamcity-playground/.teamcity/Test1_SubProject1/buildTypes/Test1_SubProject1_Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="a314f3d4-8055-41cc-b2c6-e8802f4b5dc9" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>Test</name>
  <description />
  <settings>
    <parameters />
    <build-runners />
    <vcs-settings>
      <vcs-entry-ref root-id="Test1_GithubComBradJonesTeamcityPlayground" />
    </vcs-settings>
    <requirements />
    <build-triggers />
    <cleanup />
  </settings>
</build-type>

=== brad-jones/teamcity-playground/.teamcity/Test1/buildTypes/Test1_Build1.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="7d63c45e-300f-4cde-b3d4-6a87c15216c2" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>Build1</name>
  <description>This is a build config</description>
  <settings>
    <options>
      <option name="allowExternalStatus" value="true" />
      <option name="allowPersonalBuildTriggering" value="false" />
      <option name="artifactRules" value="+:foo&#xA;+:./bar/xyz/*&#xA;+:baz" />
      <option name="branchFilter" value="+:master&#xD;&#xA;+:foo" />
      <option name="buildNumberPattern" value="1.%build.counter%-%build.vcs.number.VCSRootName%" />
      <option name="checkoutDirectory" value="/foo/bar/baz" />
      <option name="cleanBuild" value="true" />
      <option name="enableHangingBuildsDetection" value="false" />
      <option name="excludeDefaultBranchChanges" value="true" />
      <option name="showDependenciesChanges" value="true" />
    </options>
    <parameters />
    <build-runners />
    <vcs-settings>
      <vcs-entry-ref root-id="Test1_GithubComBradJonesTeamcityPlayground" />
    </vcs-settings>
    <requirements />
    <build-triggers />
    <cleanup />
  </settings>
</build-type>

=== brad-jones/teamcity-playground/.teamcity/Test1_SubProject1/buildTypes/Test1_SubProject1_BuildLin.xml
<?xml version="1.0" encoding="UTF-8"?>
<build-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="492ea0bb-e2b5-49fa-a55f-ae5a450377c8" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>Build-Lin</name>
  <description />
  <settings>
    <options>
      <option name="buildNumberPattern" value="%build.counter%-foo" />
    </options>
    <parameters />
    <build-runners>
      <runner id="RUNNER_3" name="" type="simpleRunner">
        <parameters>
          <param name="script.content" value="echo &quot;Hello World&quot;;" />
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
    </build-runners>
    <vcs-settings>
      <vcs-entry-ref root-id="Test1_GithubComBradJonesTeamcityPlayground" />
    </vcs-settings>
    <requirements />
    <build-triggers />
    <cleanup />
  </settings>
</build-type>

=== brad-jones/teamcity-playground/.teamcity/Test1/vcsRoots/Test1_Foo.xml
<?xml version="1.0" encoding="UTF-8"?>
<vcs-root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="c9bbef77-7040-43e9-9a62-0220177462f0" type="cvs" xsi:noNamespaceSchemaLocation="https://www.jetbrains.com/teamcity/schemas/2020.1/project-config.xsd">
  <name>foo</name>
  <param name="cvs-quiet-period" value="3" />
  <param name="cvs-root" value=":pserver:" />
  <param name="cvs-tag-mode" value="HEAD" />
  <param name="local-server-command" value="server" />
  <param name="module-name" value="bar" />
  <param name="secure:cvs-password" value="credentialsJSON:4328815b-28b7-43cf-b8c3-65c8584ae6e8" />
  <param name="ssh-port" value="22" />
  <param name="ssh-use-ppk" value="false" />
</vcs-root>
